# Site
title: Cyber
description: Hello World
url: "" # the base hostname & protocol for your site, e.g. https://[username].github.io/

# Github
github:
  url: "" # e.g. https://github.com/[username]

# Permalink
# https://jekyllrb.com/docs/permalinks/
permalink: /:title/

# Google services
google_analytics: "" # e.g. UA-000000-2 

sass:
  style: compressed