# Site
title: Cyber
description: Hello World

# Github
# github:
  # url: https://github.com/[username]

# Permalink
# https://jekyllrb.com/docs/permalinks/
permalink: /:title/

# Google services
# google_analytics: [Tracking ID] 

sass:
  style: compressed

plugins:
  - jekyll-seo-tag